amiq_eth: amiq_eth_object Class Reference
amiq_eth_object Class Reference
Public Member Functions
virtual void do_pack (amiq_eth_packer &) const
virtual void do_unpack (amiq_eth_packer &)
int pack (amiq_eth_packer &p) const
int unpack (amiq_eth_packer &p)
Detailed Description
Definition at line 65 of file amiq_eth_packet.cpp.
Member Function Documentation
virtual void amiq_eth_object::do_pack (amiq_eth_packer &) const [inline, virtual]
Reimplemented in amiq_eth_packet, amiq_eth_packet_arp, amiq_eth_packet_ether_type, amiq_eth_packet_ethernet_configuration_testing, amiq_eth_packet_fcoe, amiq_eth_packet_hsr_base, amiq_eth_packet_hsr_standard, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_length, amiq_eth_packet_magic, amiq_eth_packet_pause, amiq_eth_packet_pfc_pause, amiq_eth_packet_ptp_header, amiq_eth_packet_ptp_body, amiq_eth_packet_ptp_announce_message, amiq_eth_packet_ptp_sync_message, amiq_eth_packet_ptp_delay_req_message, amiq_eth_packet_ptp, and amiq_eth_packet_snap.
Definition at line 69 of file amiq_eth_packet.cpp.
Referenced by pack().
virtual void amiq_eth_object::do_unpack (amiq_eth_packer &) [inline, virtual]
Reimplemented in amiq_eth_packet, amiq_eth_packet_arp, amiq_eth_packet_ether_type, amiq_eth_packet_ethernet_configuration_testing, amiq_eth_packet_fcoe, amiq_eth_packet_hsr_base, amiq_eth_packet_hsr_standard, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_length, amiq_eth_packet_magic, amiq_eth_packet_pause, amiq_eth_packet_pfc_pause, amiq_eth_packet_ptp_header, amiq_eth_packet_ptp_body, amiq_eth_packet_ptp_announce_message, amiq_eth_packet_ptp_sync_message, amiq_eth_packet_ptp_delay_req_message, amiq_eth_packet_ptp, and amiq_eth_packet_snap.
Definition at line 73 of file amiq_eth_packet.cpp.
Referenced by unpack().
int amiq_eth_object::pack (amiq_eth_packer & p) const [inline]
Definition at line 77 of file amiq_eth_packet.cpp.
References do_pack(), and amiq_eth_packer::get_remaining_unpacked_bits().
Referenced by amiq_eth_packet::to_generic_payload().
int amiq_eth_object::unpack (amiq_eth_packer & p) [inline]
Definition at line 82 of file amiq_eth_packet.cpp.
References do_unpack(), and amiq_eth_packer::get_remaining_unpacked_bits().
The documentation for this class was generated from the following file:
/home/cristian.slav/work/amiq/projects/sv/amiq_eth/sc/amiq_eth_packet.cpp