amiq_eth: amiq_eth_packer Class Reference
amiq_eth_packer Class Reference
Public Member Functions
amiq_eth_packer ()
virtual ~amiq_eth_packer ()
virtual amiq_eth_packer & operator<< (bool a)
virtual amiq_eth_packer & operator>> (bool &a)
virtual void reset ()
virtual int get_remaining_unpacked_bits ()
void get_bytes (std::vector< char > &data)
Protected Member Functions
void allocate (int number_of_bits)
void check_size (int number_of_bits)
void inc_unpack_index (int number_of_bits)
void pack_int_n (unsigned long long data, unsigned number_of_bits)
uint64 unpack_int_n (unsigned number_of_bits)
Private Attributes
unsigned int pack_index
unsigned int unpack_index
sc_bv_base * information_bits
int size
int max_size
Detailed Description
Definition at line 26 of file amiq_eth_packer.cpp.
Constructor & Destructor Documentation
amiq_eth_packer::amiq_eth_packer () [inline]
Definition at line 123 of file amiq_eth_packer.cpp.
References information_bits, max_size, pack_index, size, and unpack_index.
virtual amiq_eth_packer::~amiq_eth_packer () [inline, virtual]
Definition at line 132 of file amiq_eth_packer.cpp.
References information_bits.
Member Function Documentation
void amiq_eth_packer::allocate (int number_of_bits) [inline, protected]
Definition at line 49 of file amiq_eth_packer.cpp.
References AMIQ_ETH_PACKING_BLOCK_SIZE, information_bits, max_size, pack_index, and size.
Referenced by check_size().
void amiq_eth_packer::check_size (int number_of_bits) [inline, protected]
Definition at line 79 of file amiq_eth_packer.cpp.
References allocate(), pack_index, and size.
Referenced by pack_int_n().
void amiq_eth_packer::get_bytes (std::vector< char > & data) [inline]
Definition at line 166 of file amiq_eth_packer.cpp.
References get_remaining_unpacked_bits().
Referenced by amiq_eth_packet_magic::get_useful_info_from_client_data(), and amiq_eth_packet_magic::set_useful_info_in_client_data().
virtual int amiq_eth_packer::get_remaining_unpacked_bits () [inline, virtual]
Definition at line 160 of file amiq_eth_packer.cpp.
References pack_index, and unpack_index.
Referenced by get_bytes(), amiq_eth_packet::get_correct_fcs(), amiq_eth_object::pack(), amiq_eth_packet::to_generic_payload(), and amiq_eth_object::unpack().
void amiq_eth_packer::inc_unpack_index (int number_of_bits) [inline, protected]
Definition at line 92 of file amiq_eth_packer.cpp.
References pack_index, and unpack_index.
Referenced by unpack_int_n().
virtual amiq_eth_packer& amiq_eth_packer::operator<< (bool a) [inline, virtual]
Definition at line 139 of file amiq_eth_packer.cpp.
References pack_int_n().
virtual amiq_eth_packer& amiq_eth_packer::operator>> (bool & a) [inline, virtual]
Definition at line 146 of file amiq_eth_packer.cpp.
References unpack_int_n().
void amiq_eth_packer::pack_int_n (unsigned long long data, unsigned number_of_bits) [inline, protected]
Definition at line 104 of file amiq_eth_packer.cpp.
References check_size(), and pack_index.
Referenced by operator<<().
virtual void amiq_eth_packer::reset () [inline, virtual]
Definition at line 152 of file amiq_eth_packer.cpp.
References pack_index, size, and unpack_index.
Referenced by amiq_eth_packet::get_correct_fcs(), amiq_eth_packet_magic::get_useful_info_from_client_data(), amiq_eth_packet_magic::set_useful_info_in_client_data(), and amiq_eth_packet::to_generic_payload().
uint64 amiq_eth_packer::unpack_int_n (unsigned number_of_bits) [inline, protected]
Definition at line 113 of file amiq_eth_packer.cpp.
References inc_unpack_index(), and unpack_index.
Referenced by operator>>().
Member Data Documentation
sc_bv_base* amiq_eth_packer::information_bits [private]
Definition at line 37 of file amiq_eth_packer.cpp.
Referenced by allocate(), amiq_eth_packer(), and ~amiq_eth_packer().
int amiq_eth_packer::max_size [private]
Definition at line 43 of file amiq_eth_packer.cpp.
Referenced by allocate(), and amiq_eth_packer().
unsigned int amiq_eth_packer::pack_index [private]
Definition at line 31 of file amiq_eth_packer.cpp.
Referenced by allocate(), amiq_eth_packer(), check_size(), get_remaining_unpacked_bits(), inc_unpack_index(), pack_int_n(), and reset().
int amiq_eth_packer::size [private]
Definition at line 40 of file amiq_eth_packer.cpp.
Referenced by allocate(), amiq_eth_packer(), check_size(), and reset().
unsigned int amiq_eth_packer::unpack_index [private]
Definition at line 34 of file amiq_eth_packer.cpp.
Referenced by amiq_eth_packer(), get_remaining_unpacked_bits(), inc_unpack_index(), reset(), and unpack_int_n().
The documentation for this class was generated from the following file:
/home/cristian.slav/work/amiq/projects/sv/amiq_eth/sc/amiq_eth_packer.cpp