amiq_eth: amiq_eth_packet_ipv4 Class Reference
amiq_eth_packet_ipv4 Class Reference
Public Member Functions
amiq_eth_packet_ipv4 ()
virtual ~amiq_eth_packet_ipv4 ()
virtual unsigned int get_pad_size_by_fields (int unsigned min_frame_size, amiq_eth_packet_ipv4_header header) const
virtual unsigned int get_pad_size () const
virtual void pack_data (amiq_eth_packer &packer) const
virtual void pack_pad (amiq_eth_packer &packer) const
virtual void pack_fcs (amiq_eth_packer &packer) const
virtual void do_pack (amiq_eth_packer &packer) const
virtual void do_unpack (amiq_eth_packer &packer)
virtual void do_pack_for_fcs (amiq_eth_packer &packer) const
virtual void do_print (ostream &out) const
virtual tlm_generic_payload * to_generic_payload () const
Public Attributes
amiq_eth_packet_ipv4_header header
amiq_eth_data * data
amiq_eth_data * pad
amiq_eth_fcs fcs
Detailed Description
Definition at line 210 of file amiq_eth_packet_ipv4.cpp.
Constructor & Destructor Documentation
amiq_eth_packet_ipv4::amiq_eth_packet_ipv4 () [inline]
Definition at line 227 of file amiq_eth_packet_ipv4.cpp.
References data, header, NULL, and pad.
virtual amiq_eth_packet_ipv4::~amiq_eth_packet_ipv4 () [inline, virtual]
Definition at line 234 of file amiq_eth_packet_ipv4.cpp.
References data, header, NULL, and pad.
Member Function Documentation
virtual void amiq_eth_packet_ipv4::do_pack (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 285 of file amiq_eth_packet_ipv4.cpp.
References amiq_eth_packet_ipv4_header::do_pack(), header, pack_data(), pack_fcs(), and pack_pad().
virtual void amiq_eth_packet_ipv4::do_pack_for_fcs (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 320 of file amiq_eth_packet_ipv4.cpp.
References amiq_eth_packet_ipv4_header::do_pack(), header, and pack_data().
virtual void amiq_eth_packet_ipv4::do_print (ostream & out) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 328 of file amiq_eth_packet_ipv4.cpp.
References AMIQ_ETH_FIELD_SEPARATOR, amiq_eth_packet_ipv4_header::do_print(), fcs, amiq_eth_packet::get_correct_fcs(), amiq_eth_packet_ipv4_header::get_data_length_in_bytes(), get_pad_size(), and header.
virtual void amiq_eth_packet_ipv4::do_unpack (amiq_eth_packer & packer) [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 295 of file amiq_eth_packet_ipv4.cpp.
References amiq_eth_do_unpack(), data, amiq_eth_packet_ipv4_header::do_unpack(), fcs, amiq_eth_packet_ipv4_header::get_data_length_in_bytes(), get_pad_size(), header, and pad.
virtual unsigned int amiq_eth_packet_ipv4::get_pad_size () const [inline, virtual]
Definition at line 256 of file amiq_eth_packet_ipv4.cpp.
References get_pad_size_by_fields(), header, and amiq_eth_packet::min_frame_size.
Referenced by do_print(), do_unpack(), and pack_pad().
virtual unsigned int amiq_eth_packet_ipv4::get_pad_size_by_fields (int unsigned min_frame_size, amiq_eth_packet_ipv4_header header) const [inline, virtual]
Definition at line 244 of file amiq_eth_packet_ipv4.cpp.
References AMIQ_ETH_ADDRESS_WIDTH, and amiq_eth_packet_ipv4_header::total_length.
Referenced by get_pad_size().
virtual void amiq_eth_packet_ipv4::pack_data (amiq_eth_packer & packer) const [inline, virtual]
Definition at line 262 of file amiq_eth_packet_ipv4.cpp.
References amiq_eth_do_pack(), data, amiq_eth_packet_ipv4_header::get_data_length_in_bytes(), and header.
Referenced by do_pack(), and do_pack_for_fcs().
virtual void amiq_eth_packet_ipv4::pack_fcs (amiq_eth_packer & packer) const [inline, virtual]
Definition at line 279 of file amiq_eth_packet_ipv4.cpp.
References amiq_eth_do_pack(), and fcs.
Referenced by do_pack().
virtual void amiq_eth_packet_ipv4::pack_pad (amiq_eth_packer & packer) const [inline, virtual]
Definition at line 270 of file amiq_eth_packet_ipv4.cpp.
References amiq_eth_do_pack(), get_pad_size(), and pad.
Referenced by do_pack().
virtual tlm_generic_payload* amiq_eth_packet_ipv4::to_generic_payload () const [inline, virtual]
Reimplemented from amiq_eth_packet.
Definition at line 351 of file amiq_eth_packet_ipv4.cpp.
References AMIQ_ETH_PACKET_IPV4_CODE.
Member Data Documentation
amiq_eth_data* amiq_eth_packet_ipv4::data
Definition at line 218 of file amiq_eth_packet_ipv4.cpp.
Referenced by amiq_eth_packet_ipv4(), do_unpack(), pack_data(), and ~amiq_eth_packet_ipv4().
amiq_eth_fcs amiq_eth_packet_ipv4::fcs
Definition at line 224 of file amiq_eth_packet_ipv4.cpp.
Referenced by do_print(), do_unpack(), and pack_fcs().
amiq_eth_packet_ipv4_header amiq_eth_packet_ipv4::header
Definition at line 215 of file amiq_eth_packet_ipv4.cpp.
Referenced by amiq_eth_packet_ipv4(), do_pack(), do_pack_for_fcs(), do_print(), do_unpack(), get_pad_size(), pack_data(), and ~amiq_eth_packet_ipv4().
amiq_eth_data* amiq_eth_packet_ipv4::pad
Definition at line 221 of file amiq_eth_packet_ipv4.cpp.
Referenced by amiq_eth_packet_ipv4(), do_unpack(), pack_pad(), and ~amiq_eth_packet_ipv4().
The documentation for this class was generated from the following file:
/home/cristian.slav/work/amiq/projects/sv/amiq_eth/sc/amiq_eth_packet_ipv4.cpp