amiq_eth: amiq_eth_packet_ptp Class Reference
amiq_eth_packet_ptp Class Reference
Public Member Functions
amiq_eth_packet_ptp ()
virtual ~amiq_eth_packet_ptp ()
virtual void pack_fcs (amiq_eth_packer &packer) const
virtual void pack_body (amiq_eth_packer &packer) const
virtual void do_pack (amiq_eth_packer &packer) const
virtual void do_unpack (amiq_eth_packer &packer)
virtual void do_pack_for_fcs (amiq_eth_packer &packer) const
virtual void do_print (ostream &out) const
virtual tlm_generic_payload * to_generic_payload () const
Public Attributes
amiq_eth_packet_ptp_header header
amiq_eth_packet_ptp_announce_message announce_message_body
amiq_eth_packet_ptp_sync_message sync_message_body
amiq_eth_packet_ptp_delay_req_message delay_req_message_body
amiq_eth_fcs fcs
Detailed Description
Definition at line 469 of file amiq_eth_packet_ptp.cpp.
Constructor & Destructor Documentation
amiq_eth_packet_ptp::amiq_eth_packet_ptp () [inline]
Definition at line 485 of file amiq_eth_packet_ptp.cpp.
References delay_req_message_body, amiq_eth_packet_ether_type::ether_type, header, SC_AMIQ_ETH_PTP, and sync_message_body.
virtual amiq_eth_packet_ptp::~amiq_eth_packet_ptp () [inline, virtual]
Definition at line 493 of file amiq_eth_packet_ptp.cpp.
References delay_req_message_body, header, and sync_message_body.
Member Function Documentation
virtual void amiq_eth_packet_ptp::do_pack (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 529 of file amiq_eth_packet_ptp.cpp.
References amiq_eth_packet_ptp_header::do_pack(), header, pack_body(), and pack_fcs().
virtual void amiq_eth_packet_ptp::do_pack_for_fcs (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 565 of file amiq_eth_packet_ptp.cpp.
References amiq_eth_packet_ptp_header::do_pack(), header, and pack_body().
virtual void amiq_eth_packet_ptp::do_print (ostream & out) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 573 of file amiq_eth_packet_ptp.cpp.
References AMIQ_ETH_FIELD_SEPARATOR, announce_message_body, delay_req_message_body, amiq_eth_packet_ptp_delay_req_message::do_print(), amiq_eth_packet_ptp_sync_message::do_print(), amiq_eth_packet_ptp_announce_message::do_print(), amiq_eth_packet_ptp_header::do_print(), fcs, amiq_eth_packet::get_correct_fcs(), header, amiq_eth_packet_ptp_header::message_type, PTP_AnnounceMessage, PTP_Delay_ReqMessage, PTP_SyncMessage, and sync_message_body.
virtual void amiq_eth_packet_ptp::do_unpack (amiq_eth_packer & packer) [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 538 of file amiq_eth_packet_ptp.cpp.
References amiq_eth_do_unpack(), announce_message_body, delay_req_message_body, amiq_eth_packet_ptp_delay_req_message::do_unpack(), amiq_eth_packet_ptp_sync_message::do_unpack(), amiq_eth_packet_ptp_announce_message::do_unpack(), amiq_eth_packet_ptp_header::do_unpack(), fcs, header, amiq_eth_packet_ptp_header::message_type, PTP_AnnounceMessage, PTP_Delay_ReqMessage, PTP_SyncMessage, and sync_message_body.
virtual void amiq_eth_packet_ptp::pack_body (amiq_eth_packer & packer) const [inline, virtual]
Definition at line 507 of file amiq_eth_packet_ptp.cpp.
References announce_message_body, delay_req_message_body, amiq_eth_packet_ptp_delay_req_message::do_pack(), amiq_eth_packet_ptp_sync_message::do_pack(), amiq_eth_packet_ptp_announce_message::do_pack(), header, amiq_eth_packet_ptp_header::message_type, PTP_AnnounceMessage, PTP_Delay_ReqMessage, PTP_SyncMessage, and sync_message_body.
Referenced by do_pack(), and do_pack_for_fcs().
virtual void amiq_eth_packet_ptp::pack_fcs (amiq_eth_packer & packer) const [inline, virtual]
Definition at line 501 of file amiq_eth_packet_ptp.cpp.
References amiq_eth_do_pack(), and fcs.
Referenced by do_pack().
virtual tlm_generic_payload* amiq_eth_packet_ptp::to_generic_payload () const [inline, virtual]
Reimplemented from amiq_eth_packet.
Definition at line 610 of file amiq_eth_packet_ptp.cpp.
References AMIQ_ETH_PACKET_PTP_CODE.
Member Data Documentation
amiq_eth_packet_ptp_announce_message amiq_eth_packet_ptp::announce_message_body
Definition at line 477 of file amiq_eth_packet_ptp.cpp.
Referenced by do_print(), do_unpack(), and pack_body().
amiq_eth_packet_ptp_delay_req_message amiq_eth_packet_ptp::delay_req_message_body
Definition at line 479 of file amiq_eth_packet_ptp.cpp.
Referenced by amiq_eth_packet_ptp(), do_print(), do_unpack(), pack_body(), and ~amiq_eth_packet_ptp().
amiq_eth_fcs amiq_eth_packet_ptp::fcs
Definition at line 482 of file amiq_eth_packet_ptp.cpp.
Referenced by do_print(), do_unpack(), and pack_fcs().
amiq_eth_packet_ptp_header amiq_eth_packet_ptp::header
Definition at line 474 of file amiq_eth_packet_ptp.cpp.
Referenced by amiq_eth_packet_ptp(), do_pack(), do_pack_for_fcs(), do_print(), do_unpack(), pack_body(), and ~amiq_eth_packet_ptp().
amiq_eth_packet_ptp_sync_message amiq_eth_packet_ptp::sync_message_body
Definition at line 478 of file amiq_eth_packet_ptp.cpp.
Referenced by amiq_eth_packet_ptp(), do_print(), do_unpack(), pack_body(), and ~amiq_eth_packet_ptp().
The documentation for this class was generated from the following file:
/home/cristian.slav/work/amiq/projects/sv/amiq_eth/sc/amiq_eth_packet_ptp.cpp