amiq_eth: amiq_eth_packet Class Reference
amiq_eth_packet Class Reference
Public Member Functions
amiq_eth_packet ()
virtual ~amiq_eth_packet ()
virtual void do_pack (amiq_eth_packer &packer, bool pack_preamble, bool pack_sfd) const
virtual void do_unpack (amiq_eth_packer &packer)
virtual void do_pack (amiq_eth_packer &packer) const
virtual void do_pack_for_fcs (amiq_eth_packer &packer) const
virtual void do_print (ostream &out) const
virtual tlm_generic_payload * to_generic_payload () const
virtual amiq_eth_fcs get_correct_fcs () const
Static Public Member Functions
static amiq_eth_fcs crc32_ccitt_seed (unsigned char *byte_data, unsigned int length, amiq_eth_fcs seed)
static amiq_eth_fcs get_crc32_ccitt (unsigned char *byte_data, unsigned int length)
static amiq_eth_fcs swap_bytes (amiq_eth_fcs data)
static amiq_eth_fcs get_crc32_802 (unsigned char *byte_data, unsigned int length)
Public Attributes
amiq_eth_preamble preamble
amiq_eth_sfd sfd
amiq_eth_address destination_address
amiq_eth_address source_address
unsigned int min_frame_size
Detailed Description
Definition at line 89 of file amiq_eth_packet.cpp.
Constructor & Destructor Documentation
amiq_eth_packet::amiq_eth_packet () [inline]
Definition at line 108 of file amiq_eth_packet.cpp.
References AMIQ_ETH_DEFAULT_MIN_FRAME_SIZE, and min_frame_size.
virtual amiq_eth_packet::~amiq_eth_packet () [inline, virtual]
Definition at line 113 of file amiq_eth_packet.cpp.
Member Function Documentation
static amiq_eth_fcs amiq_eth_packet::crc32_ccitt_seed (unsigned char * byte_data, unsigned int length, amiq_eth_fcs seed) [inline, static]
Definition at line 189 of file amiq_eth_packet.cpp.
References crc32_ccitt_table.
Referenced by get_crc32_ccitt().
virtual void amiq_eth_packet::do_pack (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_object.
Reimplemented in amiq_eth_packet_arp, amiq_eth_packet_ether_type, amiq_eth_packet_ethernet_configuration_testing, amiq_eth_packet_fcoe, amiq_eth_packet_hsr_base, amiq_eth_packet_hsr_standard, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_length, amiq_eth_packet_magic, amiq_eth_packet_pause, amiq_eth_packet_pfc_pause, amiq_eth_packet_ptp, and amiq_eth_packet_snap.
Definition at line 145 of file amiq_eth_packet.cpp.
References do_pack().
virtual void amiq_eth_packet::do_pack (amiq_eth_packer & packer, bool pack_preamble, bool pack_sfd) const [inline, virtual]
Definition at line 121 of file amiq_eth_packet.cpp.
References amiq_eth_do_pack(), destination_address, preamble, sfd, and source_address.
Referenced by do_pack(), and do_pack_for_fcs().
virtual void amiq_eth_packet::do_pack_for_fcs (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented in amiq_eth_packet_arp, amiq_eth_packet_ether_type, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_magic, amiq_eth_packet_ptp, and amiq_eth_packet_snap.
Definition at line 151 of file amiq_eth_packet.cpp.
References do_pack().
Referenced by get_correct_fcs().
virtual void amiq_eth_packet::do_print (ostream & out) const [inline, virtual]
Reimplemented in amiq_eth_packet_arp, amiq_eth_packet_ether_type, amiq_eth_packet_ethernet_configuration_testing, amiq_eth_packet_fcoe, amiq_eth_packet_hsr_base, amiq_eth_packet_hsr_standard, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_length, amiq_eth_packet_magic, amiq_eth_packet_pause, amiq_eth_packet_pfc_pause, amiq_eth_packet_ptp, and amiq_eth_packet_snap.
Definition at line 157 of file amiq_eth_packet.cpp.
References AMIQ_ETH_FIELD_SEPARATOR, destination_address, preamble, sfd, and source_address.
virtual void amiq_eth_packet::do_unpack (amiq_eth_packer & packer) [inline, virtual]
Reimplemented from amiq_eth_object.
Reimplemented in amiq_eth_packet_arp, amiq_eth_packet_ether_type, amiq_eth_packet_ethernet_configuration_testing, amiq_eth_packet_fcoe, amiq_eth_packet_hsr_base, amiq_eth_packet_hsr_standard, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_length, amiq_eth_packet_magic, amiq_eth_packet_pause, amiq_eth_packet_pfc_pause, amiq_eth_packet_ptp, and amiq_eth_packet_snap.
Definition at line 136 of file amiq_eth_packet.cpp.
References amiq_eth_do_unpack(), destination_address, preamble, sfd, and source_address.
virtual amiq_eth_fcs amiq_eth_packet::get_correct_fcs () const [inline, virtual]
Definition at line 229 of file amiq_eth_packet.cpp.
References amiq_eth_do_unpack(), do_pack_for_fcs(), get_crc32_802(), amiq_eth_packer::get_remaining_unpacked_bits(), and amiq_eth_packer::reset().
Referenced by amiq_eth_packet_snap::do_print(), amiq_eth_packet_ptp::do_print(), amiq_eth_packet_magic::do_print(), amiq_eth_packet_jumbo::do_print(), amiq_eth_packet_ipv4::do_print(), and amiq_eth_packet_arp::do_print().
static amiq_eth_fcs amiq_eth_packet::get_crc32_802 (unsigned char * byte_data, unsigned int length) [inline, static]
Definition at line 219 of file amiq_eth_packet.cpp.
References get_crc32_ccitt(), and swap_bytes().
Referenced by get_correct_fcs().
static amiq_eth_fcs amiq_eth_packet::get_crc32_ccitt (unsigned char * byte_data, unsigned int length) [inline, static]
Definition at line 199 of file amiq_eth_packet.cpp.
References AMIQ_ETH_CRC32_CCITT_SEED, and crc32_ccitt_seed().
Referenced by get_crc32_802().
static amiq_eth_fcs amiq_eth_packet::swap_bytes (amiq_eth_fcs data) [inline, static]
Definition at line 203 of file amiq_eth_packet.cpp.
Referenced by get_crc32_802().
virtual tlm_generic_payload* amiq_eth_packet::to_generic_payload () const [inline, virtual]
Reimplemented in amiq_eth_packet_arp, amiq_eth_packet_ethernet_configuration_testing, amiq_eth_packet_fcoe, amiq_eth_packet_hsr_standard, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_magic, amiq_eth_packet_pause, amiq_eth_packet_pfc_pause, amiq_eth_packet_ptp, and amiq_eth_packet_snap.
Definition at line 166 of file amiq_eth_packet.cpp.
References amiq_eth_do_unpack(), amiq_eth_packer::get_remaining_unpacked_bits(), amiq_eth_object::pack(), and amiq_eth_packer::reset().
Member Data Documentation
amiq_eth_address amiq_eth_packet::destination_address
Definition at line 100 of file amiq_eth_packet.cpp.
Referenced by amiq_eth_packet_pause::amiq_eth_packet_pause(), amiq_eth_packet_pfc_pause::amiq_eth_packet_pfc_pause(), do_pack(), do_print(), and do_unpack().
unsigned int amiq_eth_packet::min_frame_size
Definition at line 105 of file amiq_eth_packet.cpp.
Referenced by amiq_eth_packet(), and amiq_eth_packet_ipv4::get_pad_size().
amiq_eth_preamble amiq_eth_packet::preamble
Definition at line 94 of file amiq_eth_packet.cpp.
Referenced by do_pack(), do_print(), and do_unpack().
amiq_eth_sfd amiq_eth_packet::sfd
Definition at line 97 of file amiq_eth_packet.cpp.
Referenced by do_pack(), do_print(), and do_unpack().
amiq_eth_address amiq_eth_packet::source_address
Definition at line 103 of file amiq_eth_packet.cpp.
Referenced by do_pack(), do_print(), and do_unpack().
The documentation for this class was generated from the following file:
/home/cristian.slav/work/amiq/projects/sv/amiq_eth/sc/amiq_eth_packet.cpp