amiq_eth: amiq_eth_packet_jumbo Class Reference
amiq_eth_packet_jumbo Class Reference
Public Member Functions
amiq_eth_packet_jumbo ()
virtual ~amiq_eth_packet_jumbo ()
virtual void pack_fcs (amiq_eth_packer &packer) const
virtual void do_pack (amiq_eth_packer &packer) const
virtual void do_unpack (amiq_eth_packer &packer)
virtual void do_pack_for_fcs (amiq_eth_packer &packer) const
virtual void do_print (ostream &out) const
virtual tlm_generic_payload * to_generic_payload () const
Public Attributes
amiq_eth_jumbo_client_data_size client_data_size
amiq_eth_data * client_data
amiq_eth_fcs fcs
Detailed Description
Definition at line 33 of file amiq_eth_packet_jumbo.cpp.
Constructor & Destructor Documentation
amiq_eth_packet_jumbo::amiq_eth_packet_jumbo () [inline]
Definition at line 47 of file amiq_eth_packet_jumbo.cpp.
References client_data, and NULL.
virtual amiq_eth_packet_jumbo::~amiq_eth_packet_jumbo () [inline, virtual]
Definition at line 52 of file amiq_eth_packet_jumbo.cpp.
References client_data, and NULL.
Member Function Documentation
virtual void amiq_eth_packet_jumbo::do_pack (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 64 of file amiq_eth_packet_jumbo.cpp.
References amiq_eth_do_pack(), client_data, client_data_size, and pack_fcs().
virtual void amiq_eth_packet_jumbo::do_pack_for_fcs (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 96 of file amiq_eth_packet_jumbo.cpp.
References amiq_eth_do_pack(), client_data, and client_data_size.
virtual void amiq_eth_packet_jumbo::do_print (ostream & out) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 108 of file amiq_eth_packet_jumbo.cpp.
References AMIQ_ETH_FIELD_SEPARATOR, client_data_size, fcs, and amiq_eth_packet::get_correct_fcs().
virtual void amiq_eth_packet_jumbo::do_unpack (amiq_eth_packer & packer) [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 78 of file amiq_eth_packet_jumbo.cpp.
References amiq_eth_do_unpack(), client_data, client_data_size, and fcs.
virtual void amiq_eth_packet_jumbo::pack_fcs (amiq_eth_packer & packer) const [inline, virtual]
Definition at line 58 of file amiq_eth_packet_jumbo.cpp.
References amiq_eth_do_pack(), and fcs.
Referenced by do_pack().
virtual tlm_generic_payload* amiq_eth_packet_jumbo::to_generic_payload () const [inline, virtual]
Reimplemented from amiq_eth_packet.
Definition at line 128 of file amiq_eth_packet_jumbo.cpp.
References AMIQ_ETH_PACKET_JUMBO_CODE.
Member Data Documentation
amiq_eth_data* amiq_eth_packet_jumbo::client_data
Definition at line 41 of file amiq_eth_packet_jumbo.cpp.
Referenced by amiq_eth_packet_jumbo(), do_pack(), do_pack_for_fcs(), do_unpack(), and ~amiq_eth_packet_jumbo().
amiq_eth_jumbo_client_data_size amiq_eth_packet_jumbo::client_data_size
Definition at line 38 of file amiq_eth_packet_jumbo.cpp.
Referenced by do_pack(), do_pack_for_fcs(), do_print(), and do_unpack().
amiq_eth_fcs amiq_eth_packet_jumbo::fcs
Definition at line 44 of file amiq_eth_packet_jumbo.cpp.
Referenced by do_print(), do_unpack(), and pack_fcs().
The documentation for this class was generated from the following file:
/home/cristian.slav/work/amiq/projects/sv/amiq_eth/sc/amiq_eth_packet_jumbo.cpp