amiq_eth: amiq_eth_packet_magic Class Reference
amiq_eth_packet_magic Class Reference
Public Member Functions
amiq_eth_packet_magic ()
virtual ~amiq_eth_packet_magic ()
virtual void pack_fcs (amiq_eth_packer &packer) const
virtual void do_pack (amiq_eth_packer &packer) const
virtual void do_unpack (amiq_eth_packer &packer)
virtual void do_pack_for_fcs (amiq_eth_packer &packer) const
virtual void do_print (ostream &out) const
virtual void set_useful_info_in_client_data ()
virtual void get_useful_info_from_client_data ()
virtual tlm_generic_payload * to_generic_payload () const
Public Attributes
amiq_eth_address target_mac
unsigned int password_size
amiq_eth_data * password
amiq_eth_jumbo_client_data_size client_data_size
amiq_eth_data * client_data
amiq_eth_fcs fcs
int synch_stream_starting_index
Detailed Description
Definition at line 33 of file amiq_eth_packet_magic.cpp.
Constructor & Destructor Documentation
amiq_eth_packet_magic::amiq_eth_packet_magic () [inline]
Definition at line 59 of file amiq_eth_packet_magic.cpp.
References client_data, NULL, password, and synch_stream_starting_index.
virtual amiq_eth_packet_magic::~amiq_eth_packet_magic () [inline, virtual]
Definition at line 66 of file amiq_eth_packet_magic.cpp.
References client_data, NULL, and password.
Member Function Documentation
virtual void amiq_eth_packet_magic::do_pack (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 79 of file amiq_eth_packet_magic.cpp.
References amiq_eth_do_pack(), client_data, client_data_size, and pack_fcs().
virtual void amiq_eth_packet_magic::do_pack_for_fcs (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 115 of file amiq_eth_packet_magic.cpp.
References amiq_eth_do_pack(), client_data, and client_data_size.
virtual void amiq_eth_packet_magic::do_print (ostream & out) const [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 127 of file amiq_eth_packet_magic.cpp.
References AMIQ_ETH_FIELD_SEPARATOR, client_data_size, fcs, amiq_eth_packet::get_correct_fcs(), synch_stream_starting_index, and target_mac.
Referenced by get_useful_info_from_client_data().
virtual void amiq_eth_packet_magic::do_unpack (amiq_eth_packer & packer) [inline, virtual]
Reimplemented from amiq_eth_packet_ether_type.
Definition at line 95 of file amiq_eth_packet_magic.cpp.
References amiq_eth_do_unpack(), client_data, client_data_size, fcs, and get_useful_info_from_client_data().
virtual void amiq_eth_packet_magic::get_useful_info_from_client_data () [inline, virtual]
Definition at line 187 of file amiq_eth_packet_magic.cpp.
References AMIQ_ETH_ADDRESS_WIDTH, amiq_eth_do_pack(), AMIQ_ETH_MAGIC_PACKET_SYNCH_STREAM, AMIQ_ETH_MAGIC_PACKET_SYNCH_STREAM_WIDTH, AMIQ_ETH_MAGIC_PACKET_TARGET_MAC_REPETITIONS, client_data, client_data_size, do_print(), amiq_eth_packer::get_bytes(), password, password_size, amiq_eth_packer::reset(), synch_stream_starting_index, and target_mac.
Referenced by do_unpack().
virtual void amiq_eth_packet_magic::pack_fcs (amiq_eth_packer & packer) const [inline, virtual]
Definition at line 73 of file amiq_eth_packet_magic.cpp.
References amiq_eth_do_pack(), and fcs.
Referenced by do_pack().
virtual void amiq_eth_packet_magic::set_useful_info_in_client_data () [inline, virtual]
Definition at line 148 of file amiq_eth_packet_magic.cpp.
References AMIQ_ETH_ADDRESS_WIDTH, amiq_eth_do_pack(), AMIQ_ETH_MAGIC_PACKET_SYNCH_STREAM, AMIQ_ETH_MAGIC_PACKET_SYNCH_STREAM_WIDTH, AMIQ_ETH_MAGIC_PACKET_TARGET_MAC_REPETITIONS, client_data, amiq_eth_packer::get_bytes(), amiq_eth_packer::reset(), synch_stream_starting_index, and target_mac.
virtual tlm_generic_payload* amiq_eth_packet_magic::to_generic_payload () const [inline, virtual]
Reimplemented from amiq_eth_packet.
Definition at line 306 of file amiq_eth_packet_magic.cpp.
References AMIQ_ETH_PACKET_MAGIC_CODE.
Member Data Documentation
amiq_eth_data* amiq_eth_packet_magic::client_data
Definition at line 50 of file amiq_eth_packet_magic.cpp.
Referenced by amiq_eth_packet_magic(), do_pack(), do_pack_for_fcs(), do_unpack(), get_useful_info_from_client_data(), set_useful_info_in_client_data(), and ~amiq_eth_packet_magic().
amiq_eth_jumbo_client_data_size amiq_eth_packet_magic::client_data_size
Definition at line 47 of file amiq_eth_packet_magic.cpp.
Referenced by do_pack(), do_pack_for_fcs(), do_print(), do_unpack(), and get_useful_info_from_client_data().
amiq_eth_fcs amiq_eth_packet_magic::fcs
Definition at line 53 of file amiq_eth_packet_magic.cpp.
Referenced by do_print(), do_unpack(), and pack_fcs().
amiq_eth_data* amiq_eth_packet_magic::password
Definition at line 44 of file amiq_eth_packet_magic.cpp.
Referenced by amiq_eth_packet_magic(), get_useful_info_from_client_data(), and ~amiq_eth_packet_magic().
unsigned int amiq_eth_packet_magic::password_size
Definition at line 41 of file amiq_eth_packet_magic.cpp.
Referenced by get_useful_info_from_client_data().
int amiq_eth_packet_magic::synch_stream_starting_index
Definition at line 56 of file amiq_eth_packet_magic.cpp.
Referenced by amiq_eth_packet_magic(), do_print(), get_useful_info_from_client_data(), and set_useful_info_in_client_data().
amiq_eth_address amiq_eth_packet_magic::target_mac
Definition at line 38 of file amiq_eth_packet_magic.cpp.
Referenced by do_print(), get_useful_info_from_client_data(), and set_useful_info_in_client_data().
The documentation for this class was generated from the following file:
/home/cristian.slav/work/amiq/projects/sv/amiq_eth/sc/amiq_eth_packet_magic.cpp