amiq_eth: amiq_eth_packet_ether_type Class Reference
amiq_eth_packet_ether_type Class Reference
Public Member Functions
amiq_eth_packet_ether_type ()
virtual ~amiq_eth_packet_ether_type ()
virtual void do_print (ostream &out) const
virtual void pack_ether_type (amiq_eth_packer &packer) const
virtual void do_pack (amiq_eth_packer &packer) const
virtual void do_unpack (amiq_eth_packer &packer)
virtual void do_pack_for_fcs (amiq_eth_packer &packer) const
Public Attributes
ethernet_legal_protocols ether_type
Detailed Description
Definition at line 32 of file amiq_eth_packet_ether_type.cpp.
Constructor & Destructor Documentation
amiq_eth_packet_ether_type::amiq_eth_packet_ether_type () [inline]
Definition at line 40 of file amiq_eth_packet_ether_type.cpp.
References ether_type.
virtual amiq_eth_packet_ether_type::~amiq_eth_packet_ether_type () [inline, virtual]
Definition at line 45 of file amiq_eth_packet_ether_type.cpp.
Member Function Documentation
virtual void amiq_eth_packet_ether_type::do_pack (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet.
Reimplemented in amiq_eth_packet_arp, amiq_eth_packet_ethernet_configuration_testing, amiq_eth_packet_fcoe, amiq_eth_packet_hsr_base, amiq_eth_packet_hsr_standard, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_magic, amiq_eth_packet_pause, amiq_eth_packet_pfc_pause, and amiq_eth_packet_ptp.
Definition at line 67 of file amiq_eth_packet_ether_type.cpp.
References pack_ether_type().
virtual void amiq_eth_packet_ether_type::do_pack_for_fcs (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet.
Reimplemented in amiq_eth_packet_arp, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_magic, and amiq_eth_packet_ptp.
Definition at line 84 of file amiq_eth_packet_ether_type.cpp.
References pack_ether_type().
virtual void amiq_eth_packet_ether_type::do_print (ostream & out) const [inline, virtual]
Reimplemented from amiq_eth_packet.
Reimplemented in amiq_eth_packet_arp, amiq_eth_packet_ethernet_configuration_testing, amiq_eth_packet_fcoe, amiq_eth_packet_hsr_base, amiq_eth_packet_hsr_standard, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_magic, amiq_eth_packet_pause, amiq_eth_packet_pfc_pause, and amiq_eth_packet_ptp.
Definition at line 51 of file amiq_eth_packet_ether_type.cpp.
References AMIQ_ETH_FIELD_SEPARATOR, and ether_type.
virtual void amiq_eth_packet_ether_type::do_unpack (amiq_eth_packer & packer) [inline, virtual]
Reimplemented from amiq_eth_packet.
Reimplemented in amiq_eth_packet_arp, amiq_eth_packet_ethernet_configuration_testing, amiq_eth_packet_fcoe, amiq_eth_packet_hsr_base, amiq_eth_packet_hsr_standard, amiq_eth_packet_ipv4, amiq_eth_packet_jumbo, amiq_eth_packet_magic, amiq_eth_packet_pause, amiq_eth_packet_pfc_pause, and amiq_eth_packet_ptp.
Definition at line 74 of file amiq_eth_packet_ether_type.cpp.
References amiq_eth_do_unpack(), and ether_type.
virtual void amiq_eth_packet_ether_type::pack_ether_type (amiq_eth_packer & packer) const [inline, virtual]
Definition at line 60 of file amiq_eth_packet_ether_type.cpp.
References amiq_eth_do_pack(), and ether_type.
Referenced by do_pack(), and do_pack_for_fcs().
Member Data Documentation
ethernet_legal_protocols amiq_eth_packet_ether_type::ether_type
Definition at line 37 of file amiq_eth_packet_ether_type.cpp.
Referenced by amiq_eth_packet_ether_type(), amiq_eth_packet_ethernet_configuration_testing::amiq_eth_packet_ethernet_configuration_testing(), amiq_eth_packet_fcoe::amiq_eth_packet_fcoe(), amiq_eth_packet_hsr_base::amiq_eth_packet_hsr_base(), amiq_eth_packet_pause::amiq_eth_packet_pause(), amiq_eth_packet_pfc_pause::amiq_eth_packet_pfc_pause(), amiq_eth_packet_ptp::amiq_eth_packet_ptp(), do_print(), do_unpack(), and pack_ether_type().
The documentation for this class was generated from the following file:
/home/cristian.slav/work/amiq/projects/sv/amiq_eth/sc/amiq_eth_packet_ether_type.cpp