amiq_eth: amiq_eth_packet_ptp_delay_req_message Class Reference
amiq_eth_packet_ptp_delay_req_message Class Reference
Public Member Functions
amiq_eth_packet_ptp_delay_req_message ()
~amiq_eth_packet_ptp_delay_req_message ()
virtual void do_pack (amiq_eth_packer &packer) const
virtual void do_unpack (amiq_eth_packer &packer)
virtual void do_print (ostream &out) const
Public Attributes
amiq_eth_ptp_origin_timestamp * origin_timestamp
bool print_lists
Detailed Description
Definition at line 415 of file amiq_eth_packet_ptp.cpp.
Constructor & Destructor Documentation
amiq_eth_packet_ptp_delay_req_message::amiq_eth_packet_ptp_delay_req_message () [inline]
Definition at line 424 of file amiq_eth_packet_ptp.cpp.
References AMIQ_ETH_PTP_ORIGIN_TIMESTAMP_SIZE, origin_timestamp, and print_lists.
amiq_eth_packet_ptp_delay_req_message::~amiq_eth_packet_ptp_delay_req_message () [inline]
Definition at line 430 of file amiq_eth_packet_ptp.cpp.
Member Function Documentation
virtual void amiq_eth_packet_ptp_delay_req_message::do_pack (amiq_eth_packer & packer) const [inline, virtual]
Reimplemented from amiq_eth_packet_ptp_body.
Definition at line 435 of file amiq_eth_packet_ptp.cpp.
References amiq_eth_do_pack(), AMIQ_ETH_PTP_ORIGIN_TIMESTAMP_SIZE, and origin_timestamp.
Referenced by amiq_eth_packet_ptp::pack_body().
virtual void amiq_eth_packet_ptp_delay_req_message::do_print (ostream & out) const [inline, virtual]
Reimplemented from amiq_eth_packet_ptp_body.
Definition at line 457 of file amiq_eth_packet_ptp.cpp.
References AMIQ_ETH_FIELD_SEPARATOR, AMIQ_ETH_PTP_ORIGIN_TIMESTAMP_SIZE, origin_timestamp, and print_lists.
Referenced by amiq_eth_packet_ptp::do_print().
virtual void amiq_eth_packet_ptp_delay_req_message::do_unpack (amiq_eth_packer & packer) [inline, virtual]
Reimplemented from amiq_eth_packet_ptp_body.
Definition at line 445 of file amiq_eth_packet_ptp.cpp.
References amiq_eth_do_unpack(), AMIQ_ETH_PTP_ORIGIN_TIMESTAMP_SIZE, and origin_timestamp.
Referenced by amiq_eth_packet_ptp::do_unpack().
Member Data Documentation
amiq_eth_ptp_origin_timestamp* amiq_eth_packet_ptp_delay_req_message::origin_timestamp
Definition at line 418 of file amiq_eth_packet_ptp.cpp.
Referenced by amiq_eth_packet_ptp_delay_req_message(), do_pack(), do_print(), and do_unpack().
bool amiq_eth_packet_ptp_delay_req_message::print_lists
Definition at line 421 of file amiq_eth_packet_ptp.cpp.
Referenced by amiq_eth_packet_ptp_delay_req_message(), and do_print().
The documentation for this class was generated from the following file:
/home/cristian.slav/work/amiq/projects/sv/amiq_eth/sc/amiq_eth_packet_ptp.cpp